repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file dev-configs/.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config dev-configs/.black .
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config dev-configs/.flake8 .
        language: system
        types: [python]
        pass_filenames: false

      - id: xenon
        name: xenon
        entry: xenon --max-absolute B --max-modules A --max-average A .
        language: system
        types: [python]
        pass_filenames: false

      - id: bandit
        name: bandit
        entry: bandit -r .
        language: system
        types: [ python ]
        pass_filenames: false
