# Generated by Django 5.0.4 on 2024-04-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portionfood',
            name='food_item',
        ),
        migrations.AddField(
            model_name='portionfood',
            name='food_item',
            field=models.ManyToManyField(null=True, related_name='portions', to='diet.fooditem'),
        ),
    ]
