# Generated by Django 5.0.4 on 2024-04-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessexercise',
            name='muscle_group',
            field=models.CharField(
                choices=[
                    ('Shoulders', 'Shoulders'),
                    ('Chest', 'Chest'),
                    ('Back', 'Back'),
                    ('Arms', 'Arms'),
                    ('Abdominal', 'Abdominal'),
                    ('Legs', 'Legs'),
                ],
                max_length=100,
                verbose_name='fitness_exercise__muscle_group',
            ),
        ),
    ]
