# Generated by Django 5.0.3 on 2024-03-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_birth_date_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="user__birth_date"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=20, null=True, verbose_name="user__phone"
            ),
        ),
    ]
