# Generated by Django 5.0.3 on 2024-04-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_options_alter_coachprofile_experience_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="coachprofile",
            managers=[],
        ),
    ]
