# Generated by Django 5.0.4 on 2024-04-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_coachprofile_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(
                choices=[('user', 'User'), ('coach', 'Coach')], default=0, max_length=10, verbose_name='Profile type'
            ),
            preserve_default=False,
        ),
    ]
