# Generated by Django 5.0.3 on 2024-04-13 15:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="subscription",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
    ]
